Description: >
  Cloudfront distribution for UdaPeople

Parameters:
  WorkflowID_new:
    Description: Unique identifier.
    Type: String

Resources:
  
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "udapeople-${WorkflowID_new}.s3-website-us-west-2.amazonaws.com"
            Id: webpage
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID_new:
    Value: !Sub ${WorkflowID_new}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID_new
