version: 2.1
jobs:
  deploy-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y -qq update
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - attach_workspace:
          at: .
      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            export  API_URL=http://ec2-52-12-185-115.us-west-2.compute.amazonaws.com:3030
            npm i
            npm run build
            #s3Bucket=$(echo "udapeople-${CIRCLE_WORKFLOW_ID:0:7}")
            s3Bucket="udapeople-f6cac72"
            aws s3 sync dist s3://$s3Bucket/
      - persist_to_workspace:
          root: .
          paths:
            - frontend/dist

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
  # Make sure ubuntu is 20.04 in backend.yml or you will have issues with PM2. read .circleci/backend/files for more info
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 69:8e:f5:77:fd:38:4a:11:fe:9c:ae:a8:07:9f:10:94
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible tar gzip ansible nodejs npm less
            pip install awscli
      - run:
          name: Deploy backend
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml
workflows:
  default:
    jobs:
     - deploy-frontend
     - deploy-backend:
            requires: [deploy-frontend]