version: 2.1
jobs:
  deploy-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y -qq update
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - attach_workspace:
          at: .
      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            export  API_URL=http://ec2-54-186-212-157.us-west-2.compute.amazonaws.com:3030
            npm i
            npm run build
            #s3Bucket=$(echo "udapeople-${CIRCLE_WORKFLOW_ID:0:7}")
            s3Bucket="udapeople-f6cac72"
            aws s3 sync dist s3://$s3Bucket/
      - persist_to_workspace:
          root: .
          paths:
            - frontend/dist
workflows:
  default:
    jobs:
     - deploy-frontend
